name: mi_card
description: buiding...
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  assets:
    - Image/First_koala.jpg
  fonts:
    - family: Inspiration
      fonts:
        - asset: fonts/Inspiration-Regular.ttf
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
    - family: Mitr
      fonts:
        - asset: fonts/Mitr-Regular.ttf
  uses-material-design: true